import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Database, Image, Globe2, Search, CheckCircle2, AlertTriangle, ExternalLink, Clock3, ScanSearch, Download, RotateCcw } from "lucide-react";
import { API } from "../api";

type Summary={products:number,images:number,products_with_image?:number,pending_errors?:number,source:string,last_run?:any};
type Job={status:string,phase?:string,mode?:string,percent:number,scan_percent?:number,collect_percent?:number,products_found:number,products_updated:number,images_downloaded:number,errors:number,pending_errors?:number,total_skus?:number,current_index?:number,current_sku?:string,message:string,error?:string,duration_seconds?:number,started_at?:string,finished_at?:string,last_event?:string,events?:{at:string,message:string}[],eta_seconds?:number,projected_finish_at?:string,avg_seconds_per_sku?:number,throughput_skus_min?:number,collection_workers?:number,image_workers?:number,performance_mode?:string,scan_eta_seconds?:number,scan_projected_finish_at?:string,scan_avg_seconds_per_link?:number,scan_throughput_links_min?:number,scan_mdf_page?:number,scan_madeiras_page?:number,scan_mdf_found?:number,scan_madeiras_found?:number,expected_skus?:number,scan_expected_units?:number,checklist_mode?:boolean,checklist_site_total?:number,checklist_existing?:number,checklist_new?:number,checklist_missing_images?:number,checklist_retry?:number,checklist_removed?:number,scan_eta_mode?:string};

const nf=(n:any)=>Number(n||0).toLocaleString("pt-BR");
const pf=(n:any)=>`${Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})}%`;
const dt=(v?:string)=>v?new Date(v).toLocaleString("pt-BR"):"—";
const dur=(s?:number)=>{if(s===undefined||s===null)return "—"; const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=Math.round(s%60);return h?`${h}h ${m}min`:m?`${m}min ${r}s`:`${r}s`};
const eta=(s?:number)=>s===undefined||s===null?"Calculando amostra...":dur(s);

export function CatalogPage(){
  const [summary,setSummary]=useState<Summary>({products:0,images:0,source:""});
  const [job,setJob]=useState<Job>(); const [jobId,setJobId]=useState<string>();
  const [q,setQ]=useState(""); const [rows,setRows]=useState<any[]>([]);
  const loadSummary=()=>fetch(`${API}/catalog/leo/summary`).then(r=>r.json()).then(setSummary).catch(()=>{});
  const loadRows=(query="")=>fetch(`${API}/catalog/leo/products?q=${encodeURIComponent(query)}&limit=100`).then(r=>r.json()).then(setRows).catch(()=>{});
  useEffect(()=>{loadSummary();loadRows()},[]);
  useEffect(()=>{if(!jobId)return;const t=setInterval(async()=>{const r=await fetch(`${API}/catalog/leo/status/${jobId}`);if(!r.ok)return;const j=await r.json();setJob(prev=>{if(!prev)return j; if(j.phase==="scan"&&prev.phase==="scan"){return {...j,percent:Math.max(Number(prev.percent||0),Number(j.percent||0)),scan_percent:Math.max(Number(prev.scan_percent||0),Number(j.scan_percent||0)),products_found:Math.max(Number(prev.products_found||0),Number(j.products_found||0)),scan_mdf_page:Math.max(Number(prev.scan_mdf_page||0),Number(j.scan_mdf_page||0)),scan_madeiras_page:Math.max(Number(prev.scan_madeiras_page||0),Number(j.scan_madeiras_page||0)),scan_mdf_found:Math.max(Number(prev.scan_mdf_found||0),Number(j.scan_mdf_found||0)),scan_madeiras_found:Math.max(Number(prev.scan_madeiras_found||0),Number(j.scan_madeiras_found||0))};} return j;});if(j.status==="completed"||j.status==="failed"){clearInterval(t);loadSummary();loadRows(q)}},900);return()=>clearInterval(t)},[jobId]);
  async function sync(){const r=await fetch(`${API}/catalog/leo/sync`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({max_pages:250,delay_seconds:.30})});const x=await r.json();setJobId(x.job_id);setJob({status:"queued",phase:"scan",percent:0,scan_percent:0,collect_percent:0,products_found:0,products_updated:0,images_downloaded:0,errors:0,message:"Preparando sincronização..."})}
  async function checklist(){const r=await fetch(`${API}/catalog/leo/checklist`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({max_pages:250,delay_seconds:.30})});const x=await r.json();setJobId(x.job_id);setJob({status:"queued",phase:"scan",mode:"checklist",percent:0,scan_percent:0,collect_percent:0,products_found:0,products_updated:0,images_downloaded:0,errors:0,message:"Preparando Check-List completo do catálogo..."})}
  async function retryErrors(){const r=await fetch(`${API}/catalog/leo/retry-errors`,{method:"POST"});const x=await r.json();if(!x.job_id){await loadSummary();return}setJobId(x.job_id);setJob({status:"queued",phase:"collect",percent:0,scan_percent:100,collect_percent:0,products_found:x.pending||0,products_updated:0,images_downloaded:0,errors:0,total_skus:x.pending||0,message:"Preparando reprocessamento dos erros..."})}
  const running=job?.status==="queued"||job?.status==="processing"; const last=summary.last_run;
  const sourceHost=useMemo(()=>{try{return new URL(summary.source.split(" + ")[0]).hostname}catch{return "Leo Madeiras"}},[summary.source]);
  return <div className="stack">
    <section className="catalog-hero"><div><span className="eyebrow">BASE VISUAL OFICIAL</span><h2>Catálogo Leo conectado ao reconhecimento.</h2><p>Sincroniza o <b>Cod. Interno</b> e, quando ele não existir, usa o <b>Cód. LM</b>, além da descrição e imagem das categorias MDF e Madeiras. A leitura valida o total esperado antes de iniciar a coleta, evitando catálogo parcial.</p></div><div className="catalog-actions"><button className="primary big" disabled={running} onClick={sync}><RefreshCw className={running?"spin-icon":""}/> {running?"Processando...":"Sincronizar MDF + Madeiras"}</button><button className="checklist-btn" disabled={running} onClick={checklist}><CheckCircle2/> Check-List do catálogo</button>{(summary.pending_errors||0)>0&&<button className="retry-btn" disabled={running} onClick={retryErrors}><RotateCcw/> Reprocessar somente erros ({nf(summary.pending_errors)})</button>}</div></section>
    <div className="metrics catalog-metrics"><div className="metric"><Database/><div><small>SKUs do site</small><strong>{nf(summary.products)}</strong></div></div><div className="metric"><Image/><div><small>Imagens vinculadas</small><strong>{nf(summary.images)}</strong></div></div><div className="metric"><Globe2/><div><small>Fonte</small><strong className="metric-text">{sourceHost}</strong></div></div><div className="metric">{last?.status==="completed"?<CheckCircle2/>:<AlertTriangle/>}<div><small>Última sincronização</small><strong className="metric-text">{last?.finished_at?dt(last.finished_at):"Ainda não executada"}</strong></div></div></div>
    {job&&<div className={`sync-card ${job.status}`}>
      <div className="sync-head"><div><strong>{job.message}</strong><small>{job.last_event||job.error||"Acompanhamento em tempo real da sincronização."}</small></div><b>{pf(job.percent)}</b></div>
      <div className="sync-phases">
        <div className={`phase-card ${(job.scan_percent||0)>=100?"done":""}`}><div className="phase-title"><ScanSearch/><span><b>1. Leitura do catálogo</b><small>Mapeando todos os produtos antes da coleta.</small></span><strong>{pf(job.scan_percent)}</strong></div><div className="progress-track"><div className="progress-bar" style={{width:`${job.scan_percent||0}%`}}/></div></div>
        <div className={`phase-card ${(job.collect_percent||0)>=100?"done":""}`}><div className="phase-title"><Download/><span><b>2. Coleta dos dados</b><small>{job.total_skus?`${nf(job.current_index||0)} de ${nf(job.total_skus)} produtos processados`:`Aguardando finalizar a leitura...`}</small></span><strong>{pf(job.collect_percent)}</strong></div><div className="progress-track"><div className="progress-bar" style={{width:`${job.collect_percent||0}%`}}/></div></div>
      </div>
      <div className="sync-stats"><span>Total localizado <b>{nf(job.total_skus||job.products_found)}</b></span><span>Atualizados <b>{nf(job.products_updated)}</b></span><span>Imagens <b>{nf(job.images_downloaded)}</b></span><span className={job.errors?"error-stat":""}>Erros <b>{nf(job.errors)}</b></span></div>
      <div className="sync-timing"><span><Clock3/> Início <b>{dt(job.started_at)}</b></span><span><Clock3/> Fim <b>{dt(job.finished_at)}</b></span><span><Clock3/> Duração <b>{dur(job.duration_seconds)}</b></span>{job.current_sku&&<span><Database/> SKU atual <b>{job.current_sku}</b></span>}</div>
      {job.checklist_mode&&<div className="checklist-audit"><div className="checklist-audit-title"><CheckCircle2/><div><strong>Auditoria incremental do catálogo</strong><small>A leitura verifica o site inteiro, mas a coleta abre somente novos produtos, imagens faltantes e erros pendentes.</small></div></div><div className="checklist-audit-grid"><span>Produtos no site <b>{nf(job.checklist_site_total||job.products_found)}</b></span><span>Já vinculados <b>{nf(job.checklist_existing)}</b></span><span className={(job.checklist_new||0)>0?"attention":""}>Novos SKUs <b>{nf(job.checklist_new)}</b></span><span>Sem imagem <b>{nf(job.checklist_missing_images)}</b></span><span>Erros a revisar <b>{nf(job.checklist_retry)}</b></span><span>Fora do catálogo atual <b>{nf(job.checklist_removed)}</b></span></div></div>}
      {job.phase==="scan"&&<div className="eta-panel">
        <div><small>PREVISÃO DINÂMICA DA LEITURA</small><strong>{job.scan_projected_finish_at?dt(job.scan_projected_finish_at):"Estimando término..."}</strong><span>Tempo restante estimado: <b>{eta(job.scan_eta_seconds)}</b></span></div>
        <div className="eta-metrics"><span>Velocidade <b>{job.scan_throughput_links_min?`${job.scan_throughput_links_min.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})} links/min`:"—"}</b><small>{job.scan_eta_mode==="official"?"base: total oficial":"base: ritmo de páginas"}</small></span><span>MDF <b>pág. {nf(job.scan_mdf_page)} • {nf(job.scan_mdf_found)} links</b></span><span>Madeiras <b>pág. {nf(job.scan_madeiras_page)} • {nf(job.scan_madeiras_found)} links</b></span></div>
      </div>}
      {job.phase==="collect"&&<div className="eta-panel">
        <div><small>PREVISÃO DINÂMICA DE TÉRMINO</small><strong>{job.projected_finish_at?dt(job.projected_finish_at):"Estimando término..."}</strong><span>Tempo restante estimado: <b>{eta(job.eta_seconds)}</b></span></div>
        <div className="eta-metrics"><span>Média atual <b>{job.avg_seconds_per_sku?`${job.avg_seconds_per_sku.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} s/SKU`:"—"}</b></span><span>Velocidade <b>{job.throughput_skus_min?`${job.throughput_skus_min.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})} SKU/min`:"—"}</b></span><span>Processamento <b>{job.collection_workers?`${job.collection_workers} coleta + ${job.image_workers||0} imagens`:"Inicializando"}</b></span></div>
      </div>}
      {!!job.events?.length&&<details className="sync-log"><summary>Ver últimas atividades da sincronização</summary><div>{job.events.slice().reverse().map((e,i)=><p key={i}><small>{dt(e.at)}</small>{e.message}</p>)}</div></details>}
    </div>}
    <div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>{setQ(e.target.value);loadRows(e.target.value)}} placeholder="Buscar Cod. Interno, Cód. LM ou descrição no catálogo sincronizado..."/></div></div>
    <div className="catalog-grid">{rows.map(p=><article className="catalog-item" key={p.sku}><div className="catalog-image">{p.image_id?<img src={`${API}/media/${p.image_id}`} loading="lazy"/>:<Image/>}</div><div className="catalog-copy"><div className="catalog-sku">{String(p.sku).toUpperCase().startsWith("LM-")?"CÓD. LM":"COD. INTERNO"} {p.sku}</div><strong>{p.description}</strong><small>{p.manufacturer||"Fabricante não informado"}</small></div>{p.source_url&&<a href={p.source_url} target="_blank" rel="noreferrer" className="source-link"><ExternalLink size={15}/> Ver produto no site</a>}</article>)}{!rows.length&&<div className="empty-catalog"><Database/><strong>Catálogo ainda vazio</strong><span>Execute a primeira sincronização para montar a base visual.</span></div>}</div>
  </div>
}
